services:
  backend:
    container_name: invision-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL}
        POETRY_CUSTOM_SOURCE_URL: ${POETRY_CUSTOM_SOURCE_URL}
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: development
      INVISION_EMAIL: ${INVISION_EMAIL}
      INVISION_PASSWORD: ${INVISION_PASSWORD}
      DOCS_ROOT: ${DOCS_ROOT}

      PIP_INDEX_URL: ${PIP_INDEX_URL}
      POETRY_CUSTOM_SOURCE_URL: ${POETRY_CUSTOM_SOURCE_URL}
    volumes:
      - ${ROOT:-.}/docs:${DOCS_ROOT}

  frontend:
    container_name: invision-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NPM_CAFILE: ${NPM_CAFILE}
        NPM_REGISTRY_SERVER: ${NPM_REGISTRY_SERVER}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NPM_CAFILE: ${NPM_CAFILE}
      NPM_REGISTRY_SERVER: ${NPM_REGISTRY_SERVER}
    volumes:
      - ${ROOT:-.}/frontend/src:/frontend/src # Hot reloading
    command: yarn dev
