services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        CUSTOM_CA_FILE: ${CUSTOM_CA_FILE}
        PYTHON_REGISTY_URL: ${PYTHON_REGISTY_URL}
    environment:
      FLASK_ENV: production
      INVISION_EMAIL: ${INVISION_EMAIL}
      INVISION_PASSWORD: ${INVISION_PASSWORD}
      DOCS_ROOT: ${DOCS_ROOT}
      CUSTOM_CA_FILE: ${CUSTOM_CA_FILE}
    volumes:
      - ${ROOT:-.}/docs:${DOCS_ROOT}

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        CUSTOM_CA_FILE: ${CUSTOM_CA_FILE}
        NPM_REGISTRY_SERVER: ${NPM_REGISTRY_SERVER}
    environment:
      NODE_ENV: production
      CUSTOM_CA_FILE: ${CUSTOM_CA_FILE}
    ports:
      - "80:80"
