services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        CUSTOM_CA_FILE: ${CUSTOM_CA_FILE}
        PYTHON_REGISTY_URL: ${PYTHON_REGISTY_URL}
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: development
      INVISION_EMAIL: ${INVISION_EMAIL}
      INVISION_PASSWORD: ${INVISION_PASSWORD}
      DOCS_ROOT: ${DOCS_ROOT}
      CUSTOM_CA_FILE: ${CUSTOM_CA_FILE}
    volumes:
      - ${ROOT:-.}/backend/src:/backend/src # Hot reloading
      - ${ROOT:-.}/docs:${DOCS_ROOT}

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        CUSTOM_CA_FILE: ${CUSTOM_CA_FILE}
        NPM_REGISTRY_SERVER: ${NPM_REGISTRY_SERVER}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CUSTOM_CA_FILE: ${CUSTOM_CA_FILE}
    volumes:
      - ${ROOT:-.}/frontend/src:/frontend/src # Hot reloading
    command: yarn dev
