services:
  backend:
    container_name: invision-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: development
      INVISION_EMAIL: ${INVISION_EMAIL}
      INVISION_PASSWORD: ${INVISION_PASSWORD}
      DOCS_ROOT: ${DOCS_ROOT}
    volumes:
      - ${ROOT:-.}/docs:${DOCS_ROOT}

  frontend:
    container_name: invision-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ${ROOT:-.}/frontend/src:/frontend/src # Hot reloading
    command: yarn dev
